### ISSUE TITLE
enum problem

### ISSUE THREAD

**Issue by klaasbrant** [dalenewman/Cfg-NET#3]
Is used an enum in cfgnode like this:
        public enum ConnectionType
        {
            SQLServer,
            ODBC,
            Oracle,
            OleDb,
            DB2,
            MySQL,
            PostgreSql
        }

        [Cfg]
        public ConnectionType Type { get; set; }

Serialize works OK but when I load again it sets an error:

Could not set type to DB2 inside DB item. The given key was not present in the dictionary.

enums are not supported?

The class works great! It did take me a while to figure out that serialize uses the format you use in load and by default (if you never loaded) it is XML. A simple empty JSON load put the Cfg into JSON mode: cfg.load("{}"); :-)

**Comment by dalenewman** [comment]
No currently they are not supported.  You would this as an alternative:

```csharp
[Cfg(domain="SQLServer,ODBC,Oracle,OleDb,DB2,MySQL,PostgreSql",required=true)]
public string Type {get; set; }
```
Enums would be cool though, so I will look into support for it.  Thanks for using it, and I appreciate the feedback regarding the `Serialize` method.

Thanks

**Comment by klaasbrant** [comment]
Great, I modified the code to use literals as suggested. Thanks for the suggestion. I looked into the Cfg class myself but it is not that easy to integrate an enum. :-o
